### ISSUE TITLE
Stack level too deep

### ISSUE THREAD

**Issue by biow0lf** [railsware/http_logger#18]
Hi,

Commit 474ff6057e504d74dc0e105c21e35e1f4ca49a67 breaks rspec systems specs (commit before works).

Example spec:

```
# frozen_string_literal: true

require "rails_helper"

describe "Sign in features" do
  it "when user successfully sign in" do
    create(:user, email: "me@example.com", password: "password")

    visit "/"

    click_link "Sign In"

    fill_in "user[email]", with: "me@example.com"
    fill_in "user[password]", with: "password"

    click_button "Sign in"

    expect(page).to have_content("Signed in successfully.")

    expect(current_path).to eq("/characters")
  end
end
```

Fail with

```
SystemStackError:
  stack level too deep
# ./spec/system/sign_ins_spec.rb:5:in `<top (required)>'
# -e:1:in `<main>'
No examples found.

Finished in 0.00009 seconds (files took 2.1 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

Env:
gem version: 0.6.0
ruby: 2.7.0
rails 6-0-stable from cd0ab2446418215dd9d48e062a2b4db25624eed3
rspec from master.

I can provide minimal rails app for reproduction.

Example fail: https://circleci.com/gh/evemonk/evemonk/698?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by bogdan** [comment]
Can you give a full backtrace of the error?

**Comment by benjaminwols** [comment]
Same problem here

Traceback (most recent call last):
       16: from appsignal (2.10.2) lib/appsignal/hooks/net_http.rb:24:in `block in request'
       15: from http_logger (0.6.0) lib/http_logger.rb:195:in `request'
       14: from http_logger (0.6.0) lib/http_logger.rb:45:in `perform'
       13: from http_logger (0.6.0) lib/http_logger.rb:58:in `perform'
       12: from http_logger (0.6.0) lib/http_logger.rb:196:in `block in request'
       11: from appsignal (2.10.2) lib/appsignal/hooks/net_http.rb:20:in `request'
       10: from appsignal (2.10.2) lib/appsignal/helpers/instrumentation.rb:429:in `instrument'
        9: from appsignal (2.10.2) lib/appsignal/hooks/net_http.rb:24:in `block in request'
        8: from http_logger (0.6.0) lib/http_logger.rb:195:in `request'
        7: from http_logger (0.6.0) lib/http_logger.rb:45:in `perform'
        6: from http_logger (0.6.0) lib/http_logger.rb:67:in `perform'
        5: from http_logger (0.6.0) lib/http_logger.rb:60:in `ensure in perform'
        4: from http_logger (0.6.0) lib/http_logger.rb:124:in `require_logging?'
        3: from http_logger (0.6.0) lib/http_logger.rb:128:in `ignored?'
        2: from http_logger (0.6.0) lib/http_logger.rb:80:in `request_url'
        1: from activesupport (6.0.2.1) lib/active_support/core_ext/numeric/conversions.rb:107:in `to_s'
SystemStackError (stack level too deep)

**Comment by bogdan** [comment]
Can you show the content of `hooks/net_http.rb`?

**Comment by benjaminwols** [comment]
@bogdan https://github.com/appsignal/appsignal-ruby/blob/master/lib/appsignal/hooks/net_http.rb

**Comment by bogdan** [comment]
It seems like alias method chain pattern is conflicting with the usage of `prepend` : https://ruby-doc.org/core-2.6.1/Module.html#method-i-prepend

You can fix that by switching from alias method chain to prepend in your hook like:

``` ruby
module RequestHook
  def request(request, body = nil, &block)
            Appsignal.instrument(
              "request.net_http",
              "#{request.method} #{use_ssl? ? "https" : "http"}://#{request["host"] || address}"
            ) do
              super(request, body, &block)
            end
   end
end

def install
  Net::HTTP.prepend(RequestHook)
end

```


I am not sure how to solve problem in general yet.

Do you think you are fine with this workaround?

**Comment by gyfis** [comment]
Hey all, we've encountered the same issue and dealt with it by making a fork of `http_logger` using `alias chaining` instead of `prepend` to properly work with New Relic etc. Here's the fork: [wallmine/http_logger](https://github.com/wallmine/http_logger). I think the approach proposed by the folks in [appsignal/appsignal-ruby#603](https://github.com/appsignal/appsignal-ruby/issues/603), e.g. making this configurable, is a much better solution, but we don't need it for now.

**Comment by bogdan** [comment]
@gyfis it seems like we'd better stick to the alias method chain approach because of the fact that so many libraries do it this way and we want to be compatible with them.

Can you open a PR with your changes?

**Comment by gyfis** [comment]
@bogdan Sure! Here's the PR: https://github.com/railsware/http_logger/pull/21

**Comment by damienlethiec** [comment]
Hi there :) I still get the issue on my side !
