### ISSUE TITLE
NameError: uninitialized constant HttpLogger::FakeWeb

### ISSUE THREAD

**Issue by mklocek** [railsware/http_logger#22]
I have an environment where:
- I use http_logger (0.6.0)
- I use webmock
- I don't use fakeweb

And I observe this error on an HTTP request:

```
NameError:
       uninitialized constant HttpLogger::FakeWeb
     # /gems/gems/http_logger-0.6.0/lib/http_logger.rb:149:in `request_uri_as_string'
     # /gems/gems/http_logger-0.6.0/lib/http_logger.rb:136:in `fakeweb?'
     # /gems/gems/http_logger-0.6.0/lib/http_logger.rb:124:in `require_logging?'
     # /gems/gems/http_logger-0.6.0/lib/http_logger.rb:60:in `perform'
     # /gems/gems/http_logger-0.6.0/lib/http_logger.rb:45:in `perform'
     # /gems/gems/http_logger-0.6.0/lib/http_logger.rb:195:in `request'
```

fakeweb dependency was removed in https://github.com/railsware/http_logger/commit/474ff6057e504d74dc0e105c21e35e1f4ca49a67 but there are still some places in the code where FakeWeb is used and are not covered with specs.

BTW. There is at least one more weird thing in the linked commit: why would Gemfile.lock be added to .gitignore? 🤔

**Comment by bogdan** [comment]
Fixed in 0de8d22be7f657b3c5c94bbec63ca1a6931e26cd
